In [3]:
from sklearn import svm, metrics
from sklearn.model_selection import train_test_split, GridSearchCV
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def model(datapath):
    df = pd.read_csv(datapath)
    #df_s = df.sort_values('label')
    y = df["label"].values
    labels = df["label"] 
    X = df.drop("label",axis=1).values/255
    #print(df.head())
    #print(df.shape)
    print(y)
    print(X)
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
    svc = svm.SVC()
    parameters = {"gamma":[0.0001, 0.0005, 0.001, 0.005, 0.01, 0.1]}
    clf = GridSearchCV(svc, parameters, verbose=1)
    clf.fit(X_train,y_train)
    print("Best estimator found by grid search:")
    print(clf.best_estimator_)
    test_score = clf.score(X_test,y_test)
    y_pred = clf.predict(X_test)
    print(test_score)
    print(metrics.classification_report(y_test, y_pred, 
                                        target_names=["0","1","2","3","4","5","6","7","8","9"]))
    print(metrics.confusion_matrix(y_test, y_pred, labels=range(10)))
    

In [4]:
DATAPATH = "data/digits.csv"
model(DATAPATH)

[1 0 1 ... 4 7 9]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Fitting 3 folds for each of 6 candidates, totalling 18 fits


/usr/local/lib/python3.5/dist-packages/sklearn/model_selection/_split.py:1943: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done  18 out of  18 | elapsed: 12.7min finished


Best estimator found by grid search:
SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
0.9475
              precision    recall  f1-score   support

           0       0.96      0.97      0.97       195
           1       0.96      0.97      0.96       234
           2       0.95      0.95      0.95       214
           3       0.94      0.93      0.94       183
           4       0.95      0.94      0.95       202
           5       0.96      0.95      0.95       182
           6       0.94      0.98      0.96       189
           7       0.96      0.93      0.94       218
           8       0.95      0.92      0.93       189
           9       0.90      0.94      0.92       194

   micro avg       0.95      0.95      0.95      2000
   macro avg       0.95      0.95      0.95      2000
weighted avg       0.95      