In [1]:
from sklearn import svm, metrics
from sklearn.model_selection import train_test_split, GridSearchCV
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

def model(datapath):
    df = pd.read_csv(datapath)
    #df_s = df.sort_values('label')
    y = df["label"].values
    labels = df["label"] 
    X = df.drop("label",axis=1).values/255
    #print(df.head())
    #print(df.shape)
    print(y)
    print(X)
    X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
    parameters = {'C': [1000], 'kernel': ['poly'], 'gamma': [0.001]}
    svc = svm.SVC(parameters)
    #parameters = {"gamma":[0.0001, 0.0005, 0.001, 0.005, 0.01, 0.1]}
    parameters = [
        {'C': [1, 10, 100, 1000], 'kernel': ['linear']},
        {'C': [1, 10, 100, 1000], 'kernel': ['rbf'], 'gamma': [0.001, 0.0001]},
        {'C': [1, 10, 100, 1000], 'kernel': ['poly'], 'degree': [2, 3, 4], 'gamma': [0.001, 0.0001]},
        {'C': [1, 10, 100, 1000], 'kernel': ['sigmoid'], 'gamma': [0.001, 0.0001]}
        ]
    
    clf = GridSearchCV(svc, parameters, verbose=2, n_jobs=-1)
    #clf=svc
    clf.fit(X_train,y_train)
    print("Best estimator found by grid search:")
    print(clf.best_estimator_)
    return clf, X_test, y_test


def model_estimation(fitted_model, X_test, y_test):
    test_score = fitted_model.score(X_test,y_test)
    y_pred = fitted_model.predict(X_test)
    print(test_score)
    print(metrics.classification_report(y_test, y_pred, 
                                        target_names=["0","1","2","3","4","5","6","7","8","9"]))
    print(metrics.confusion_matrix(y_test, y_pred, labels=range(10)))
    plt.clf()


In [2]:
DATAPATH = "data/digits.csv"
clf,X_test, y_test = model(DATAPATH)

[1 0 1 ... 4 7 9]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Fitting 3 folds for each of 44 candidates, totalling 132 fits


[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:  7.9min
[Parallel(n_jobs=-1)]: Done 132 out of 132 | elapsed: 64.7min finished


Best estimator found by grid search:
SVC(C=1000, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=2, gamma=0.001, kernel='poly',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)


In [3]:
model_estimation(clf, X_test, y_test)

0.9575
             precision    recall  f1-score   support

          0       0.97      0.99      0.98       206
          1       0.96      0.96      0.96       244
          2       0.95      0.95      0.95       220
          3       0.97      0.94      0.95       207
          4       0.94      0.96      0.95       191
          5       0.97      0.95      0.96       182
          6       0.94      0.98      0.96       192
          7       0.97      0.95      0.96       194
          8       0.98      0.93      0.95       194
          9       0.93      0.98      0.95       170

avg / total       0.96      0.96      0.96      2000

[[203   0   0   0   1   0   1   0   1   0]
 [  0 235   3   0   1   0   3   1   1   0]
 [  0   1 209   1   4   0   2   1   1   1]
 [  1   1   3 194   0   4   2   1   1   0]
 [  0   0   1   0 184   0   1   0   0   5]
 [  1   0   1   4   0 172   3   0   0   1]
 [  2   0   1   0   1   0 188   0   0   0]
 [  2   1   2   1   2   0   0 184   0   2]
 [  0   5 

<Figure size 432x288 with 0 Axes>

In [7]:
results = pd.DataFrame(clf.cv_results_)
print(clf.best_score_)
display(results)

0.9515


C:\Users\usami\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:122: FutureWarning: You are accessing a training score ('split0_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\usami\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:122: FutureWarning: You are accessing a training score ('split1_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\usami\Anaconda3\lib\site-packages\sklearn\utils\deprecation.py:122: FutureWarning: You are accessing a training score ('split2_train_score'), which will not be available by default any more in 0.21. If you need training scores, please set return_train_score=True
  warnings.warn(*warn_args, **warn_kwargs)
C:\Users\usami\Anaconda3\lib\site-packages\sklearn\util

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       11.008101      0.110070         7.888770        0.045987       1   
1       11.082582      0.170012         7.916274        0.013027      10   
2       11.156388      0.264457         7.917129        0.093096     100   
3       11.658526      0.077262         7.896836        0.029250    1000   
4       33.308290      0.119270        16.106756        0.056728       1   
5       79.108022      0.993484        23.457244        0.172545       1   
6       14.646064      0.071234         9.866976        0.111950      10   
7       30.154826      0.017725        15.758705        0.075290      10   
8       11.654849      0.092454         8.286287        0.097575     100   
9       14.069683      0.077032         9.743914        0.250492     100   
10      12.226166      0.832359         8.749156        0.667163    1000   
11      11.396653      0.072060         8.210306        0.092989    1000   
12     100.177976      1.100762        25.648433        0.227124       1   
13     104.928430      2.344988        25.401310        0.824545       1   
14     103.666025      0.716722        25.041988        0.347084       1   
15     103.862886      0.227119        25.346643        0.071488       1   
16     106.240499      0.159743        24.521986        0.063045       1   
17     103.793777      1.345091        24.434125        0.114012       1   
18      46.349456      0.602771        17.554645        0.006247      10   
19     102.343859      0.527899        24.364655        0.106979      10   
20      95.639480      0.963661        24.019138        0.224182      10   
21     101.974430      0.127367        24.563569        0.062375      10   
22     102.524282      0.004349        24.277131        0.101513      10   
23     101.338366      0.743387        24.306758        0.150457      10   
24      19.785568      0.207011        10.242606        0.078978     100   
25      94.260016      0.174529        23.732370        0.192878     100   
26      54.576341      0.390014        17.844826        0.133074     100   
27     100.961525      0.091376        24.080480        0.171628     100   
28      95.066120      0.510115        23.579147        0.104072     100   
29     100.175343      0.071588        24.154570        0.185257     100   
30      14.081410      0.063246         8.122583        0.098830    1000   
31      44.704998      0.192394        17.193826        0.018027    1000   
32      25.065502      0.080993        10.705150        0.094037    1000   
33     105.552206      0.135535        24.272254        0.049402    1000   
34      65.119844      2.533156        19.005080        0.030621    1000   
35     100.515969      0.451418        24.116920        0.123914    1000   
36      40.360256      0.302958        18.235550        0.169556       1   
37      94.241254      0.164978        23.892628        0.041947       1   
38      16.894412      0.265173        10.922932        0.076766      10   
39      39.568776      0.127655        18.030803        0.142155      10   
40      11.271776      0.163819         8.109519        0.084727     100   
41      17.234093      0.132786        10.928236        0.089297     100   
42      10.994478      0.113919         7.848840        0.044665    1000   
43      10.582525      1.154089         7.135741        1.388370    1000   

   param_kernel param_gamma param_degree  \
0        linear         NaN          NaN   
1        linear         NaN          NaN   
2        linear         NaN          NaN   
3        linear         NaN          NaN   
4           rbf       0.001          NaN   
5           rbf      0.0001          NaN   
6           rbf       0.001          NaN   
7           rbf      0.0001          NaN   
8           rbf       0.001          NaN   
9           rbf      0.0001          NaN   
10          rbf       0.001          NaN   
11          rbf      0.0001          NaN   
12         

In [8]:
from sklearn.model_selection import cross_val_score
svm_ = svm.SVC(C=1000,gamma=0.001,kernel="poly",degree=2)
df = pd.read_csv(DATAPATH)
y = df["label"].values
labels = df["label"] 
X = df.drop("label",axis=1).values/255
scores=cross_val_score(svm_,X,y,cv=5)

In [9]:
print(scores)

[0.96255617 0.95852074 0.9645     0.95397699 0.95743615]
